"""Generate worker/src/favicon.ts as the amber clock icon (dark rounded square,
glowing amber ring + hands) shown in the design reference. Crisp, supersampled
render so it stays sharp at favicon sizes. Re-run to regenerate.

Run with the Windows Python that has Pillow installed, e.g.
  %LOCALAPPDATA%\\Programs\\Python\\Python313\\python.exe assets/gen_amber_favicon.py
"""
import base64
import math
from PIL import Image, ImageDraw, ImageFilter

SS = 8          # supersample factor
SIZE = 64       # final favicon size
S = SIZE * SS   # working canvas size

BG = (10, 11, 16, 255)          # dark rounded-square background
AMBER = (245, 166, 60, 255)     # amber ring / hands
AMBER_HI = (241, 180, 107, 255) # lighter amber highlight
GLOW = (245, 166, 60)           # glow colour (alpha applied separately)

cx = cy = S / 2

# --- base transparent canvas ---
img = Image.new("RGBA", (S, S), (0, 0, 0, 0))
draw = ImageDraw.Draw(img)

# rounded-square dark background
pad = int(S * 0.02)
radius = int(S * 0.22)
draw.rounded_rectangle([pad, pad, S - pad, S - pad], radius=radius, fill=BG)

# --- amber glow layer (drawn on its own canvas, blurred, composited under ring) ---
glow = Image.new("RGBA", (S, S), (0, 0, 0, 0))
gd = ImageDraw.Draw(glow)
ring_r = S * 0.33
ring_w = int(S * 0.06)
gd.ellipse([cx - ring_r, cy - ring_r, cx + ring_r, cy + ring_r],
           outline=GLOW + (255,), width=int(ring_w * 2.0))
glow = glow.filter(ImageFilter.GaussianBlur(radius=S * 0.045))
img = Image.alpha_composite(img, glow)
draw = ImageDraw.Draw(img)

# --- hour tick marks (subtle) ---
for i in range(12):
    ang = math.radians(i * 30 - 90)
    r_out = ring_r - ring_w * 0.9
    r_in = r_out - (S * 0.03 if i % 3 == 0 else S * 0.018)
    x1 = cx + r_out * math.cos(ang)
    y1 = cy + r_out * math.sin(ang)
    x2 = cx + r_in * math.cos(ang)
    y2 = cy + r_in * math.sin(ang)
    a = 200 if i % 3 == 0 else 110
    draw.line([x1, y1, x2, y2], fill=AMBER[:3] + (a,), width=int(S * 0.012))

# --- amber ring ---
draw.ellipse([cx - ring_r, cy - ring_r, cx + ring_r, cy + ring_r],
             outline=AMBER, width=ring_w)

# --- clock hands ---
def hand(angle_deg, length, width, color):
    ang = math.radians(angle_deg - 90)
    x = cx + length * math.cos(ang)
    y = cy + length * math.sin(ang)
    draw.line([cx, cy, x, y], fill=color, width=width)
    # rounded cap
    r = width / 2
    draw.ellipse([x - r, y - r, x + r, y + r], fill=color)

# minute hand pointing up (12), hour hand pointing to ~5 o'clock — matches reference
hand(0, ring_r * 0.78, int(S * 0.035), AMBER_HI)     # minute (up)
hand(150, ring_r * 0.52, int(S * 0.045), AMBER)      # hour (down-right)

# center hub
hub = int(S * 0.03)
draw.ellipse([cx - hub, cy - hub, cx + hub, cy + hub], fill=AMBER_HI)

# --- downsample to final size ---
final = img.resize((SIZE, SIZE), Image.LANCZOS)
final.save(r"C:\dev\clocked\assets\_fav_amber_preview.png")

b64 = base64.b64encode(open(r"C:\dev\clocked\assets\_fav_amber_preview.png", "rb").read()).decode()

ts = (
    "// Auto-generated by assets/gen_amber_favicon.py.\n"
    "// The clocked amber clock icon, served at /favicon.ico so browsers that\n"
    "// fetch it directly get a real image.\n"
    'const PNG_B64 =\n  "' + b64 + '";\n\n'
    "export function faviconResponse(): Response {\n"
    "  const bin = atob(PNG_B64);\n"
    "  const bytes = new Uint8Array(bin.length);\n"
    "  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);\n"
    "  return new Response(bytes, {\n"
    "    headers: {\n"
    '      "content-type": "image/png",\n'
    '      "cache-control": "public, max-age=86400",\n'
    "    },\n"
    "  });\n"
    "}\n"
)
open(r"C:\dev\clocked\worker\src\favicon.ts", "w", newline="\n").write(ts)
print("wrote worker/src/favicon.ts (", len(b64), "b64 chars )")
