"""Generate worker/src/favicon.ts from assets/clocked.ico so the dashboard's
favicon is the exact same clock as the tray icon. Re-run after changing the icon.
"""
import base64
from PIL import Image

im = Image.open(r"C:\dev\clocked\assets\clocked.ico").resize((64, 64), Image.LANCZOS).convert("RGBA")
im.save(r"C:\dev\clocked\assets\_fav_preview.png")
b64 = base64.b64encode(open(r"C:\dev\clocked\assets\_fav_preview.png", "rb").read()).decode()

ts = (
    "// Auto-generated by assets/gen_favicon.py from assets/clocked.ico.\n"
    "// The clocked clock icon (same as the Windows tray icon), served at\n"
    "// /favicon.ico so browsers that fetch it directly get a real image.\n"
    'const PNG_B64 =\n  "' + b64 + '";\n\n'
    "export function faviconResponse(): Response {\n"
    "  const bin = atob(PNG_B64);\n"
    "  const bytes = new Uint8Array(bin.length);\n"
    "  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);\n"
    "  return new Response(bytes, {\n"
    "    headers: {\n"
    '      "content-type": "image/png",\n'
    '      "cache-control": "public, max-age=86400",\n'
    "    },\n"
    "  });\n"
    "}\n"
)
open(r"C:\dev\clocked\worker\src\favicon.ts", "w", newline="\n").write(ts)
print("wrote worker/src/favicon.ts (", len(b64), "b64 chars )")
